### ISSUE TITLE
Kindly provide the steps to configure 

### ISSUE THREAD

**Issue by arungpillai** [afalfallaj/gimdow_homeassistant#1]
Thanks for creating a custom component for gimdow lock, I have installed this lock and used your code it is working well, 
 If you can make this as HACS addon lot of people will get benefit.

**Comment by webhostsg** [comment]
This really works great!!!! Should make it available on HACS.
Steps for those interested in using it

1. Copy `custom_components/gimdow` into your HomeAssistant `config/custom_components` folder. I downloaded this repo unzipped it and used the FTP addon to upload.
2. Add the following to your HomeAssistant `configuration.yaml` file
```
lock:
  - platform: gimdow
    name: ""
    device_id: ""
    url: https://openapi.tuyaeu.com
    client_id: !secret tuya_access_id 
    api_key: !secret tuya_access_key
```
  
Obtain the `client_id` and `api_key` from https://platform.tuya.com
![CleanShot 2024-10-06 at 21 32 25](https://github.com/user-attachments/assets/049d9d46-5fdc-4699-8ffb-07729c5226c5)

Obtain the `device_id` from Tuya Developer Platform: https://platform.tuya.com
![CleanShot 2024-10-06 at 21 40 39](https://github.com/user-attachments/assets/79c950f3-fd34-4be0-905c-bca46343c7ef)

3. Reboot HomeAssistant
4. The lock will be under HA's Developer tool under states.

![CleanShot 2024-10-06 at 21 35 30](https://github.com/user-attachments/assets/9ef05404-3d53-4b69-9744-644257324d76)

You can now create automation for the lock. For example. `lock.lock` or `lock.unlock`.

**Comment by avigrinberg** [comment]
Hi,
i follow your steps and i can't find the lock in the Developer tool.
i get this error message in the HA log

Logger: homeassistant.components.lock
Source: helpers/entity_platform.py:239
integration: Lock (documentation, issues)
First occurred: 23:50:21 (1 occurrences)
Last logged: 23:50:21

The gimdow platform for the lock integration does not support platform setup. Please remove it from your config.

**Comment by avigrinberg** [comment]
can you help me please?

**Comment by webhostsg** [comment]
> can you help me please?

Did you upload the `custom_components/gimdow` into HomeAssistant's `config/custom_components` folder? And make sure the platform is set to `gimdow` in your `configuration.yaml` the `device_id` need to match  the `Device ID` in your Tuya Developer Platform account. And also the URL needs to match the server you are using.
One last thing, you need the Tuya Official HomeAssistant Integration needs to be active and configured. If it's not active the lock would not work.

```
lock:
  - platform: gimdow
    name: ""
    device_id: ""
    url: https://openapi.tuyaeu.com
    client_id: !secret tuya_access_id 
    api_key: !secret tuya_access_key
```
![CleanShot 2024-12-18 at 03 36 48](https://github.com/user-attachments/assets/a38c0166-cea3-44f4-a259-4a4d5df1a8e7)

![CleanShot 2024-12-18 at 03 38 17](https://github.com/user-attachments/assets/9c50e355-f74a-4f8d-9bd4-69f2d2f37870)
